### ISSUE TITLE
Consider renaming main library file for consistency

### ISSUE THREAD

**Issue by Aqudi** [tinyjin/lottie-thorvg#1]
Hey there! 👋

The Dart document (https://dart.dev/guides/libraries/create-library-packages) recommends that the main library file for a package should be named `lib/<package-name>.dart`. However, the current entry point file for the lottie-thorvg package is named `lottiel.dart`, which deviates from the recommended naming convention.

For consistency with the guidelines and better discoverability, it might be worth considering renaming the `lottiel.dart` file to `lottie-thorvg.dart`.

Thank you!

**Comment by tinyjin** [comment]
@Aqudi Thanks for reaching out to the project.

The purpose of the naming was to align the import statement with `lottie-flutter` as much as possible.

However, I have overlooked the proper package standard. I fully agree with the guidelines and will ensure that this is corrected in next release. The import statement will be `import 'package:lottie_thorvg/lottie_thorvg.dart';`

Thank you.
